### ISSUE TITLE
Add api group to clusterrole's first rule in config/manager

### ISSUE THREAD

**Issue by semmet95** [kubevela/kube-trigger#47]
**Describe the bug**
Getting the error
```
The ClusterRole "kube-trigger-manager-role" is invalid: rules[0].apiGroups: Required value: resource rules must supply at least one api group
```
when applying `config/manager/role.yaml` file.

**To Reproduce**
1. Follow the [Quick Start](https://github.com/kubevela/kube-trigger/blob/main/examples/README.md#quick-start) guide.
2. Apply all the files in `config/crd`, `config/definition`, and `config/manager` respectively.
3. `kubectl apply -f` will throw the error when trying to apply `role.yaml`.

**Expected behavior**
Successful creation of `ClusterRole` `kube-trigger-manager-role`

**Kube Trigger Version**
- kube-trigger version: `1.0.0` (kube-trigger addon)

**Cluster information**
- Minikube version: `v1.30.1`
- Kuberentes version: `v1.24.13`
- Kubevela version: `v1.8.1`

**Additional context**
I enabled the `kube-trigger` addon after installing `kubevela` .

**Comment by semmet95** [comment]
I have already updated the ClusterRole and tested the changes, along with some minor updates to the Quick Start instructions. The changes are ready for a PR.

**Comment by FogDong** [comment]
Hi @semmet95 
Welcome to contribute and create a PR for this!
